Matriz(W) = $[[\alpha/(\alpha+1), 1/(\alpha+1)],[\alpha/(\alpha+1), 1/(\alpha+1)]]$ $\hspace{0.5cm}$ con $\alpha < 0 \\ $ 
Verificar que -> Ln(Matriz(I)+Matriz(W)) = Ln(2)Matriz(W)


In [9]:
import numpy as np

In [10]:
a = 1
matW = [[(a/(a+1.0)), (1.0/(a+1.0))], [(a/(a+1.0)), (1.0/(a+1.0))]]
matI2 = np.identity(2)
print(matW)
print(matI2)

[[0.5, 0.5], [0.5, 0.5]]
[[1. 0.]
 [0. 1.]]


In [11]:
mat_IpW = matW + matI2 
print(mat_IpW)

[[1.5 0.5]
 [0.5 1.5]]


In [12]:
#Calculando ln(I+W) = lnIW
eigvals, Q = np.linalg.eig(mat_IpW)
Qinv = np.linalg.inv(Q)
matLambda= np.diag(np.log(eigvals))
lnIW = np.real(np.matmul(np.matmul(Q,matLambda),Qinv))
print(lnIW)

[[0.34657359 0.34657359]
 [0.34657359 0.34657359]]


In [ ]:
#Calculando ln(2)W
ln2_W = np.log(2)*np.array(matW)
print(ln2_W)

[[0.34657359 0.34657359]
 [0.34657359 0.34657359]]
